services:
  - type: web
    name: mass-approver
    env: python
    region: oregon
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    pythonVersion: "3.11.9"
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
